title: '#9 Dream'
description: >
  transnational soundscapes, song networks, audiotopias
url: "https://9dream.netlify.app"
paginate:	1 # The number of posts to show per page on your homepage
name: "Martin Roberts"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
  - jekyll-compose
  - jekyll-spaceship