title: Bribes et morceaux
description: >
  Unpublished papers
url: "https://imagine.netlify.com"
paginate:	1 # The number of posts to show per page on your homepage
name: "Martin Roberts"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
